services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - POSTGRES_HOST=database
    ports:
      - "3030:3000"
    networks:
      - web
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWD
      - POSTGRES_DB=$POSTGRES_DATABASE
    #ports:
    #  - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - web
networks:
  web:
    driver: bridge
